GestionEmployeeAppWeb/Controllers/DepartementController.cs
using GestionEmployeeAppWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GestionEmployeeAppWeb.Controllers
{
    public class DepartementController : Controller
    {
        private readonly EmployeeContext _Db;

        public DepartementController(EmployeeContext Db)
        {
            _Db = Db;
        }
        public IActionResult Index()
        {
            try
            {
                var depList = from a in _Db.Departements
                              select new Departements
                              {
                                  DepId = a.DepId,
                                  DepartementName = a.DepartementName,
                              };
                return View(depList);
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        public IActionResult Create(Departements obj)
        {
            return View(obj);
        }

        [HttpPost]
        public async Task<IActionResult> AddDepartement(Departements obj)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (obj.DepId == 0)
                    {
                        _Db.Departements.Add(obj);
                        await _Db.SaveChangesAsync();
                    }
                    else
                    {
                        _Db.Entry(obj).State = EntityState.Modified;
                        await _Db.SaveChangesAsync();

                    }

                    return RedirectToAction("Index");
                }
                return View();
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index");
            }
        }

        public async Task<IActionResult> DeleteDepartement(int id)
        {
            try
            {
                
                var dep = await _Db.Departements.FindAsync(id);
                if (dep != null)
                {
                    _Db.Departements.Remove(dep);
                    await _Db.SaveChangesAsync();
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index");
            }
        }
    }
}

GestionEmployeeAppWeb/Controllers/EmployeeController.cs
using GestionEmployeeAppWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GestionEmployeeAppWeb.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly EmployeeContext _Db;

        public EmployeeController(EmployeeContext Db)
        {
            _Db = Db;
        }
        public IActionResult EmployeeList()
        {
            try
            {
                //var empList = _Db.Employees.ToList();
                var empList = from a in _Db.Employees
                              join b in _Db.Departements
                              on a.DepId equals b.DepId
                              into Dep
                              from b in Dep.DefaultIfEmpty()

                              select new Employee
                              {
                                  EmpId=a.EmpId,
                                  EmpNom=a.EmpNom,
                                  EmpPrenom=a.EmpPrenom,
                                  Age=a.Age,
                                  DepId=a.DepId,

                                  DepartementName=b==null? "":b.DepartementName
                              };
                return View(empList);
            }
            catch(Exception ex)
            {
                return View();
            }
            
        }

        public IActionResult Create(Employee obj)
        {
            loadDDL();
            return View(obj);
        }

        [HttpPost]
        public async Task<IActionResult> AddEmployees(Employee obj)
        {
            try {
                if (ModelState.IsValid)
                {
                    if (obj.EmpId == 0)
                    {
                        _Db.Employees.Add(obj);
                        await _Db.SaveChangesAsync();
                    }
                    else
                    {
                        _Db.Entry(obj).State = EntityState.Modified;
                        await _Db.SaveChangesAsync();

                    }

                    return RedirectToAction("EmployeeList");
                }
                return View();
            }
            catch(Exception ex) {
                return RedirectToAction("EmployeeList");
            }
        }

        public async Task<IActionResult> DeleteEmployee(int id)
        {
            try
            {
                var emp =await  _Db.Employees.FindAsync(id);
                if (emp!=null)
                {
                    _Db.Employees.Remove(emp);
                    await _Db.SaveChangesAsync();
                }
                return RedirectToAction("EmployeeList");
            }
            catch (Exception ex)
            {
                return RedirectToAction("EmployeeList");
            }
        }
        private void loadDDL()
        {
            try
            {
                List<Departements> depList = new List<Departements>();
                depList = _Db.Departements.ToList();
                depList.Insert(0, new Departements { DepId = 0, DepartementName = "Please select" });
                ViewBag.DepList = depList;
            }
            catch (Exception ex)
            {
                
            }
        }
    }
}

GestionEmployeeAppWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GestionEmployeeAppWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand col-md-4" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-home"></i> GESTION EMPLOYEES</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item col-md-3">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Departement" asp-action="Index"><i class="fas fa-th-list"></i> DEPARTEMENTS</a>
                        </li>
                        <li class="nav-item col-md-3">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="EmployeeList"><i class="fas fa-users"></i> EMPLOYEES</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2022 - GESTION EMPLOYEE -
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/font-awesome/js/all.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>